apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "llmevaluator.labels" . | nindent 4 }}
  name: {{ template "llmevaluator.name" . }}-config
data:
  generator.yaml: | 
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/generator.yaml" | nindent 4 }}
  {{ end }}