import os
import subprocess


# Specification path
INPUT_SPEC = "llm-evaluator/interface-specification.yml"

# Code output path
PATH_FOLDER = "llm-evaluator/src/generated/"

init_message = f"""
SETTING PARAMETERS:

    Specification_Path = {INPUT_SPEC}
    Output_folder_Path = {PATH_FOLDER}

"""
print(init_message)

# Securely generating API code structure using subprocess
subprocess.run(["fastapi-codegen", "--input", INPUT_SPEC, "--output", PATH_FOLDER], check=True)
print("Generating the API code structure.........")

print("______________________________________________________________________________\n")

# Install pre-commit hooks
print("Installing 'pre-commit'.......")
cwd1 = os.getcwd()
os.chdir(f"{cwd1}/llm-evaluator")
subprocess.run(["pre-commit", "install"], check=True)

print("______________________________________________________________________________\n")

# Add noqa for autogenerated code
print("Adding 'noqa' for autogenerated code......")
cwd2 = os.getcwd()
os.chdir(f"{cwd2}/src/generated")
subprocess.run(["ruff", "check", ".", "--add-noqa"], check=True)

print("______________________________________________________________________________\n")

print("\n\n SETUP COMPLETED!\n")
